"""weekly_audit.py — produce the single markdown file the user reads each week.

Runs failure_audit and seed_audit, then concatenates their markdown into one
report at `reports/weekly_YYYY-MM-DD.md`. This is the file the user opens
during their 5-minute Monday review.

Usage:
    python -m scripts.weekly_audit                    # full: failures + seed re-render + QA
    python -m scripts.weekly_audit --skip-seed        # failures only (fast, no $)
    python -m scripts.weekly_audit --seed-dry-run     # failures + seed schema check only
    python -m scripts.weekly_audit --skip-failure     # seed only

By default this is the only command the user needs to run weekly.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

GIFPT_AI_ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = GIFPT_AI_ROOT / "reports"


def run_subscript(name: str, args: list[str]) -> int:
    cmd = [sys.executable, "-m", f"scripts.{name}", *args]
    print(f"[weekly_audit] running: {' '.join(cmd)}")
    return subprocess.call(cmd, cwd=str(GIFPT_AI_ROOT))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--days", type=int, default=7, help="Failure window in days")
    parser.add_argument("--skip-failure", action="store_true")
    parser.add_argument("--skip-seed", action="store_true")
    parser.add_argument("--seed-dry-run", action="store_true",
                        help="Run seed audit in dry-run mode (no render, no QA)")
    parser.add_argument("--seed-no-qa", action="store_true",
                        help="Render seeds but skip vision QA")
    args = parser.parse_args()

    today = datetime.now().astimezone().strftime("%Y-%m-%d")
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    # Run sub-audits
    if not args.skip_failure:
        rc = run_subscript("failure_audit", ["--days", str(args.days)])
        if rc != 0:
            print(f"[weekly_audit] failure_audit exited {rc} — continuing")

    if not args.skip_seed:
        seed_args: list[str] = []
        if args.seed_dry_run:
            seed_args.append("--dry-run")
        elif args.seed_no_qa:
            seed_args.append("--no-qa")
        rc = run_subscript("seed_audit", seed_args)
        if rc != 0:
            print(f"[weekly_audit] seed_audit exited {rc} — continuing")

    # Stitch together
    failure_md = REPORTS_DIR / f"failure_audit_{today}.md"
    seed_md = REPORTS_DIR / f"seed_audit_{today}.md"
    out_md = REPORTS_DIR / f"weekly_{today}.md"

    parts: list[str] = []
    parts.append(f"# Weekly Audit — {today}")
    parts.append("")
    parts.append("> Generated by `python -m scripts.weekly_audit`. "
                 "Read top-to-bottom (~5 min), fill in action items, then move on.")
    parts.append("")
    parts.append("## How to read this")
    parts.append("")
    parts.append("1. **Failure section** — anything flagged (`!`) is a domain whose fail rate spiked. Check the top failing slug for a pattern.")
    parts.append("2. **Seed section** — any `FAIL` row means few-shot prompts using that example are degrading the model. Fix or remove the example.")
    parts.append("3. **Action items** at the bottom of each section — fill them in, then queue the work.")
    parts.append("")
    parts.append("---")
    parts.append("")

    if failure_md.exists():
        parts.append(failure_md.read_text())
        parts.append("")
        parts.append("---")
        parts.append("")
    elif not args.skip_failure:
        parts.append("_failure_audit report missing — sub-script likely errored. Check stderr above._")
        parts.append("")

    if seed_md.exists():
        parts.append(seed_md.read_text())
    elif not args.skip_seed:
        parts.append("_seed_audit report missing — sub-script likely errored. Check stderr above._")

    out_md.write_text("\n".join(parts) + "\n")
    print(f"[weekly_audit] wrote {out_md}")
    print(f"[weekly_audit] open it: open {out_md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
